api:
  github:
    host: https://api.github.com
    token: 'Bearer TOKEN'

spring:
  data:
    jpa:
      repositories:
        enabled: false
    jdbc:
      repositories:
        enabled: false
    r2dbc:
      repositories:
        enabled: false
  cloud:
    refresh:
      enabled: false

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
logging:
  level:
    com:
      eheinen:
        pullrequestmanager:
          api:
            github: debug
